file(COPY ${ISHMEM_SOURCE_DIR}/ishmem.h DESTINATION "${ISHMEM_BUILD_ROOT}/${CMAKE_INSTALL_INCLUDEDIR}")
file(COPY ${ISHMEM_SOURCE_DIR}/ishmemx.h DESTINATION "${ISHMEM_BUILD_ROOT}/${CMAKE_INSTALL_INCLUDEDIR}")

file(COPY ${ISHMEM_SOURCE_DIR}/ishmem DESTINATION "${ISHMEM_BUILD_ROOT}/${CMAKE_INSTALL_INCLUDEDIR}"
    FILES_MATCHING PATTERN *.h)
